# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .build APP

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  check:
    outputs:
      status: ${{ steps.changed-files-specific.outputs.any_changed }}
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v44
        with:
          files: src/torino-restaurant-app/** # Alternatively using: `docs/**`
  build:
    needs: check
    if: needs.check.outputs.status == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: build and test lint
        working-directory: ./src/torino-restaurant-app
        run: |
          npm install yarn
          yarn install
          yarn lint
